//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyncSelector {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncSelector() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SyncSelector", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 calling01,calling02,calling03 的本地化字符串。
        /// </summary>
        internal static string Calling_ClientPostNames {
            get {
                return ResourceManager.GetString("Calling_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryCalling 的本地化字符串。
        /// </summary>
        internal static string Calling_DataSourceName {
            get {
                return ResourceManager.GetString("Calling_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/calling.js 的本地化字符串。
        /// </summary>
        internal static string Calling_DataSourceURL {
            get {
                return ResourceManager.GetString("Calling_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string Calling_DefaultText {
            get {
                return ResourceManager.GetString("Calling_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 的本地化字符串。
        /// </summary>
        internal static string Calling_DefaultValue {
            get {
                return ResourceManager.GetString("Calling_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 education 的本地化字符串。
        /// </summary>
        internal static string Education_ClientPostNames {
            get {
                return ResourceManager.GetString("Education_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryEducation 的本地化字符串。
        /// </summary>
        internal static string Education_DataSourceName {
            get {
                return ResourceManager.GetString("Education_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/Education.js 的本地化字符串。
        /// </summary>
        internal static string Education_DataSourceURL {
            get {
                return ResourceManager.GetString("Education_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string Education_DefaultText {
            get {
                return ResourceManager.GetString("Education_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string Education_DefaultValue {
            get {
                return ResourceManager.GetString("Education_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 jobCalling 的本地化字符串。
        /// </summary>
        internal static string JobCallings_ClientPostNames {
            get {
                return ResourceManager.GetString("JobCallings_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryJobCallings 的本地化字符串。
        /// </summary>
        internal static string JobCallings_DataSourceName {
            get {
                return ResourceManager.GetString("JobCallings_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/jobCallings.js 的本地化字符串。
        /// </summary>
        internal static string JobCallings_DataSourceURL {
            get {
                return ResourceManager.GetString("JobCallings_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string JobCallings_DefaultText {
            get {
                return ResourceManager.GetString("JobCallings_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 的本地化字符串。
        /// </summary>
        internal static string JobCallings_DefaultValue {
            get {
                return ResourceManager.GetString("JobCallings_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 jobCategory01,jobCategory02 的本地化字符串。
        /// </summary>
        internal static string JobCategories_ClientPostNames {
            get {
                return ResourceManager.GetString("JobCategories_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryJobCategories 的本地化字符串。
        /// </summary>
        internal static string JobCategories_DataSourceName {
            get {
                return ResourceManager.GetString("JobCategories_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/jobCategories.js 的本地化字符串。
        /// </summary>
        internal static string JobCategories_DataSourceURL {
            get {
                return ResourceManager.GetString("JobCategories_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string JobCategories_DefaultText {
            get {
                return ResourceManager.GetString("JobCategories_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 的本地化字符串。
        /// </summary>
        internal static string JobCategories_DefaultValue {
            get {
                return ResourceManager.GetString("JobCategories_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 province,city,area 的本地化字符串。
        /// </summary>
        internal static string Location_ClientPostNames {
            get {
                return ResourceManager.GetString("Location_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryLocation 的本地化字符串。
        /// </summary>
        internal static string Location_DataSourceName {
            get {
                return ResourceManager.GetString("Location_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/Location.js 的本地化字符串。
        /// </summary>
        internal static string Location_DataSourceURL {
            get {
                return ResourceManager.GetString("Location_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string Location_DefaultText {
            get {
                return ResourceManager.GetString("Location_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 的本地化字符串。
        /// </summary>
        internal static string Location_DefaultValue {
            get {
                return ResourceManager.GetString("Location_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 marketCategories01,marketCategories02,marketCategories03 的本地化字符串。
        /// </summary>
        internal static string MarketCategories_ClientPostNames {
            get {
                return ResourceManager.GetString("MarketCategories_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryMarketCategories 的本地化字符串。
        /// </summary>
        internal static string MarketCategories_DataSourceName {
            get {
                return ResourceManager.GetString("MarketCategories_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/MarketCategories.js 的本地化字符串。
        /// </summary>
        internal static string MarketCategories_DataSourceURL {
            get {
                return ResourceManager.GetString("MarketCategories_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string MarketCategories_DefaultText {
            get {
                return ResourceManager.GetString("MarketCategories_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 的本地化字符串。
        /// </summary>
        internal static string MarketCategories_DefaultValue {
            get {
                return ResourceManager.GetString("MarketCategories_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sex 的本地化字符串。
        /// </summary>
        internal static string Sex_ClientPostNames {
            get {
                return ResourceManager.GetString("Sex_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 arySex 的本地化字符串。
        /// </summary>
        internal static string Sex_DataSourceName {
            get {
                return ResourceManager.GetString("Sex_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/Sex.js 的本地化字符串。
        /// </summary>
        internal static string Sex_DataSourceURL {
            get {
                return ResourceManager.GetString("Sex_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string Sex_DefaultText {
            get {
                return ResourceManager.GetString("Sex_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string Sex_DefaultValue {
            get {
                return ResourceManager.GetString("Sex_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shopProdcutCategories01,shopProdcutCategories02,shopProdcutCategories03,shopProdcutCategories04,shopProdcutCategories05 的本地化字符串。
        /// </summary>
        internal static string ShopProductCategories_ClientPostNames {
            get {
                return ResourceManager.GetString("ShopProductCategories_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryShopProductCategories 的本地化字符串。
        /// </summary>
        internal static string ShopProductCategories_DataSourceName {
            get {
                return ResourceManager.GetString("ShopProductCategories_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/ShopProductCategories.js 的本地化字符串。
        /// </summary>
        internal static string ShopProductCategories_DataSourceURL {
            get {
                return ResourceManager.GetString("ShopProductCategories_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string ShopProductCategories_DefaultText {
            get {
                return ResourceManager.GetString("ShopProductCategories_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -1 的本地化字符串。
        /// </summary>
        internal static string ShopProductCategories_DefaultValue {
            get {
                return ResourceManager.GetString("ShopProductCategories_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 workexp 的本地化字符串。
        /// </summary>
        internal static string WorkExp_ClientPostNames {
            get {
                return ResourceManager.GetString("WorkExp_ClientPostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aryWorkExp 的本地化字符串。
        /// </summary>
        internal static string WorkExp_DataSourceName {
            get {
                return ResourceManager.GetString("WorkExp_DataSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /js/data/WorkExp.js 的本地化字符串。
        /// </summary>
        internal static string WorkExp_DataSourceURL {
            get {
                return ResourceManager.GetString("WorkExp_DataSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string WorkExp_DefaultText {
            get {
                return ResourceManager.GetString("WorkExp_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string WorkExp_DefaultValue {
            get {
                return ResourceManager.GetString("WorkExp_DefaultValue", resourceCulture);
            }
        }
    }
}
